### PR TITLE
README update

### PR DESCRIPTION
**Pull request by Ph3nol**

### CODE REVIEW

**Comment by Ph3nol** [comment]
README updated with new Redis and RabbitMQ checkers + Some typos fixes.

**Comment by lsmith77** [comment]
are you also going to submit a PR for LiipMonitorBundle?

**Comment by Ph3nol** [comment]
I can do it if you want. Let me know.

**Comment by Ph3nol** [comment]
https://github.com/liip/LiipMonitorBundle/pull/40

**Pull request merged**
